# -*- coding: utf-8 -*-
# Generated by scripts/generate_from_specs.py
from __future__ import unicode_literals

# Levels

BASIC_SKILLS = "H64ZOHfi"
LOWER_PRIMARY = "wnarlxKo"
LOWER_SECONDARY = "eLt0Mbu4"
PRESCHOOL = "FOhG0ib"
PROFESSIONAL = "ZrgBU73s"
TERTIARY = "FYxwbxts"
UPPER_PRIMARY = "BkGYi3lD"
UPPER_SECONDARY = "ZEjiwvOb"
WORK_SKILLS = "Z#97dvst"

INICIAL_COMPLETO = "icdhf1b2"
SEMI_INICIAL = "sio21is2"

choices = (
    (BASIC_SKILLS, "Basic Skills"),
    (LOWER_PRIMARY, "Lower Primary"),
    (LOWER_SECONDARY, "Lower Secondary"),
    (PRESCHOOL, "Preschool"),
    (PROFESSIONAL, "Professional"),
    (TERTIARY, "Tertiary"),
    (UPPER_PRIMARY, "Upper Primary"),
    (UPPER_SECONDARY, "Upper Secondary"),
    (WORK_SKILLS, "Work Skills"),
    (INICIAL_COMPLETO, "Inicial Completo"),
    (SEMI_INICIAL, "semi Inicial"),
)

LEVELSLIST = [
    BASIC_SKILLS,
    LOWER_PRIMARY,
    LOWER_SECONDARY,
    PRESCHOOL,
    PROFESSIONAL,
    TERTIARY,
    UPPER_PRIMARY,
    UPPER_SECONDARY,
    WORK_SKILLS,
    INICIAL_COMPLETO,
    SEMI_INICIAL,
]
