# -*- coding: utf-8 -*-
# Generated by scripts/generate_from_specs.py
from __future__ import unicode_literals

# Subjects

SCIENCE_TECHNOLOGY = "st32u31y"
SCIENCE_TECHNOLOGYC1 = "st32u31y.stxwx2c1"
SCIENCE_TECHNOLOGYC1_D1 = "st32u31y.stxwx2c1.stadcc1d1"
SCIENCE_TECHNOLOGYC1_D2 = "st32u31y.stxwx2c1.stadcc1d2"
SCIENCE_TECHNOLOGYC1_D3 = "st32u31y.stxwx2c1.stadcc1d3"
CIENCIAS_SOCIALES = "cs32u31y"
CIENCIAS_SOCIALESC1 = "cs32u31y.cs3fg4c1"
CIENCIAS_SOCIALESC1_D1 = "cs32u31y.cs3fg4c1.csfec1d1"
CIENCIAS_SOCIALESC1_D2 = "cs32u31y.cs3fg4c1.csfec1d2"
CIENCIAS_SOCIALESC2 = "cs32u31y.cs3fg4c2"
CIENCIAS_SOCIALESC2_D1 = "cs32u31y.cs3fg4c2.csfec2d1"
CIENCIAS_SOCIALESC2_D2 = "cs32u31y.cs3fg4c2.csfec2d2"

choices = (
    (SCIENCE_TECHNOLOGY, "CIENCIA Y TECNOLOGÍA"),
    (SCIENCE_TECHNOLOGYC1, "INDAGA MEDIANTE MÉTODOS CIENTÍFICOS PARA CONSTRUIR SUS CONOCIMIENTOS"),
    (SCIENCE_TECHNOLOGYC1_D1, "Hace preguntas que expresan su curiosidad sobre los objetos, seres vivos, hechos o fenómenos que acontecen en su ambiente."),
    (SCIENCE_TECHNOLOGYC1_D2, "Obtiene información sobre las características de los objetos y materiales que explora a través de sus sentidos. Usa algunos objetos y herramientas en su exploración."),
    (SCIENCE_TECHNOLOGYC1_D3, "Comunica los descubrimientos que hace cuando explora. Utiliza gestos o señas, movimientos corporales o lo hace oralmente."),
    (CIENCIAS_SOCIALES, "CIENCIAS SOCIALES GB"),
    (CIENCIAS_SOCIALESC1, "CONSTRUYE INTERPRETACIONES HISTÓRICAS."),
    (CIENCIAS_SOCIALESC1_D1, "Utiliza fuentes históricas para obtener información sobre un hecho o proceso histórico, desde el origen de la humanidad hasta las civilizaciones del mundo clásico y desde los primeros pobladores hasta los Estados regionales en los Andes centrales."),
    (CIENCIAS_SOCIALESC1_D2, "Clasifica diferentes tipos de fuentes históricas y obtiene información de estas respecto de hechos o procesos históricos, desde el origen de la humanidad hasta las civilizaciones del mundo clásico y desde los primeros pobladores hasta los Estados regionales en los Andes centrales"),
    (CIENCIAS_SOCIALESC2, "GESTIONA RESPONSABLEMENTE EL ESPACIO Y EL AMBIENTE."),
    (CIENCIAS_SOCIALESC2_D1, "Describe los elementos naturales y sociales de los grandes espacios en el Perú: mar, costa, sierra y selva, considerando las actividades económicas realizadas por los actores sociales y sus características demográficas"),
    (CIENCIAS_SOCIALESC2_D2, "La información y herramientas cartográficas para ubicar diversos elementos naturales y sociales de los espacios geográficos. "),
)

SUBJECTSLIST = [
    SCIENCE_TECHNOLOGY,
    SCIENCE_TECHNOLOGYC1,
    SCIENCE_TECHNOLOGYC1_D1,
    SCIENCE_TECHNOLOGYC1_D2,
    SCIENCE_TECHNOLOGYC1_D3,
    CIENCIAS_SOCIALES,
    CIENCIAS_SOCIALESC1,
    CIENCIAS_SOCIALESC1_D1,
    CIENCIAS_SOCIALESC1_D2,
    CIENCIAS_SOCIALESC2,
    CIENCIAS_SOCIALESC2_D1,
    CIENCIAS_SOCIALESC2_D2,
]
