// -*- coding: utf-8 -*-
// Generated by scripts/generate_from_specs.py
// Subjects

export default {
    SCIENCE_TECHNOLOGY: "st32u31y",
    SCIENCE_TECHNOLOGYC1: "st32u31y.stxwx2c1",
    SCIENCE_TECHNOLOGYC1_D1: "st32u31y.stxwx2c1.stadcc1d1",
    SCIENCE_TECHNOLOGYC1_D2: "st32u31y.stxwx2c1.stadcc1d2",
    SCIENCE_TECHNOLOGYC1_D3: "st32u31y.stxwx2c1.stadcc1d3",
    CIENCIAS_SOCIALES: "cs32u31y",
    CIENCIAS_SOCIALESC1: "cs32u31y.cs3fg4c1",
    CIENCIAS_SOCIALESC1_D1: "cs32u31y.cs3fg4c1.csfec1d1",
    CIENCIAS_SOCIALESC1_D2: "cs32u31y.cs3fg4c1.csfec1d2",
    CIENCIAS_SOCIALESC2: "cs32u31y.cs3fg4c2",
    CIENCIAS_SOCIALESC2_D1: "cs32u31y.cs3fg4c2.csfec2d1",
    CIENCIAS_SOCIALESC2_D2: "cs32u31y.cs3fg4c2.csfec2d2",
};
